### ISSUE TITLE
[Bug] "You are entering the support channel!" is displayed when clicking replied message, switching between channels, tabs and search results

### ISSUE THREAD

**Issue by KaKi87** [Equicord/Equibop#10]
### Discord Account

kaki87

### Operating System

Pop OS 22.04

### Linux Only ~ Desktop Environment

GNOME on Xorg

### What happens when the bug or crash occurs?

The "You are entering the support channel!" popup appears unexpectedly.

### What is the expected behaviour?

The popup doesn't appear.

### How do you recreate this bug or crash?

1. Go to support channel ;
2. Expect popup ;
3. Click to reply to a message ;
4. Click on "replying to" ;
5. See unexpected popup.
---
1. Go to support channel ;
2. Expect popup ;
3. Go to other channel ;
4. Go gack to support channel ;
6. See unexpected popup.
---
1. Enable ChannelTabs ;
2. Go to support channel ;
3. Expect popup ;
4. Open new tab ;
5. Go to other channel ;
7. Click previous tab ;
8. See unexpected popup.
---
1. Go to support channel ;
2. Press `Ctrl`-`F` ;
3. Press `Enter` ;
4. Click "jump" on a message ;
5. See unexpected popup.

### Debug Logs

```
Not a crash.
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Equibop and Equicord versions
- [X] This issue occurs on an official release (not just the AUR packages)

**Comment by thororen1234** [comment]
its supposed to show up in support channels however not more than once

**Comment by thororen1234** [comment]
It is enabled by VCSupport and will now do the popup only once unless discord is reloaded.
