### ISSUE TITLE
[Feature Request] Flatpak support

### ISSUE THREAD

**Issue by rowbawts** [Equicord/Equibop#11]
### Motivation

Since Sunroof is now EOL and was distributed through Flathub, a new Flatpak release through there for this project would be nice.

### Solution

A Flatpak release distributed through Flathub.

### Alternatives

Continuing Sunroof use until this is implemented.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Equicord feature request

**Comment by KrstlSkll69** [comment]
FlatPak/Flathub Support is being worked on but it'll prolly take some time
![DiscordCanary_YqIEHXm5Zm](https://github.com/user-attachments/assets/c629088b-bb62-48e7-a9c6-719337974aac)

**Comment by KrystalSkullOfficial** [comment]
FlatPak/Flathub Support is being worked on but it'll prolly take some time
![DiscordCanary_YqIEHXm5Zm](https://github.com/user-attachments/assets/d7778463-059a-4827-9a71-f73ec806f96e)

**Comment by vMohammad24** [comment]
close dis

**Comment by kittenvr** [comment]
any updates?

**Comment by KrystalSkullOfficial** [comment]
When there is an update it the be announced on our discord server

**Comment by thororen1234** [comment]
https://github.com/flathub/flathub/pull/5464
