### ISSUE TITLE
[Feature Request] Hide Messages plugin should hide profile pictures of mentions when MentionAvatars is on

### ISSUE THREAD

**Issue by Jeremy5909** [Equicord/Equibop#12]
### Motivation

It would make more sense because HideMessages usually hides pfp's

### Solution

pfps would be hidden when showing an avatar with mentionavatars

### Alternatives

i dont think there is good alternative

### Additional context

![image](https://github.com/user-attachments/assets/97f09984-592f-4319-9181-8698a6420b9a)
these should be solid colors like the pfps

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [ ] This is not a Equicord feature request

**Comment by KrystalSkullOfficial** [comment]
>     * [x]  This is not a Equicord feature request

Plz no plugin request those can be made in the server
https://discord.com/channels/1173279886065029291/1173334591302553631

**Comment by Jeremy5909** [comment]
idk if i should make a new issue for this but it should also work in group chats
![image](https://github.com/user-attachments/assets/61c4521f-d83f-486a-a6ad-f29d7b4bbec9)

**Comment by Jeremy5909** [comment]
> > ```
> > * [x]  This is not a Equicord feature request
> > ```
> 
> Plz no plugin request those can be made in the server https://discord.com/channels/1173279886065029291/1173334591302553631

i uncheckmarked that. i thought that channel was only for new plugins

**Comment by KrystalSkullOfficial** [comment]
> > > ```
> > > * [x]  This is not a Equicord feature request
> > > ```
> > 
> > 
> > Plz no plugin request those can be made in the server https://discord.com/channels/1173279886065029291/1173334591302553631
> 
> i uncheckmarked that. i thought that channel was only for new plugins

it can also be used for additions for already existing plugins

**Comment by Jeremy5909** [comment]
Ok mb

**Comment by thororen1234** [comment]
This isn't supposed to hide all of that it named hide messages for a reason

**Comment by thororen1234** [comment]
Group dm icons won't be added and aren't planned

**Comment by thororen1234** [comment]
And mentions are probably not going to be fixed as it hides the message so if you reveal it it's on you as the mentioned user may is not hidden in the hidden message because it's a mention of that makes sense
