### ISSUE TITLE
[Bug] Unable to right click text on message input

### ISSUE THREAD

**Issue by Chaotic-Oven** [Equicord/Equibop#17]
### Operating System

Fedora 40

### Linux Only ~ Desktop Environment

GNOME on Wayland

### What happens when the bug or crash occurs?

Right click options do not appear when right clicking text in the message input, instead it just moves the text cursor (video provided)
[Screencast from 2024-07-30 14-34-33.webm](https://github.com/user-attachments/assets/71f88d45-5846-4eda-bbdc-f1755b33baef)

### What is the expected behaviour?

Right click menu appears in message input like normal

### How do you recreate this bug or crash?

1. Open Equibop
2. Navigate to a place where messages can be typed
3. Type in message box
4. Right click on the text

### Debug Logs

```
Found package-type: rpm
Checking for update
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
Update for version 2.0.6 is not available (latest version: 2.0.6, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
[21899:0730/143751.939279:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[21899:0730/143751.954636:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[21899:0730/143751.966668:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!

```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Equibop and Equicord versions
- [X] This issue occurs on an official release (not just the AUR packages)

**Comment by thororen1234** [comment]
Fixed in [c507239](https://github.com/Equicord/Equicord/commit/c50723910647cb149c90bd93eac206ab1eec4815) - I missed a single IS_VESKTOP statement so I didnt add IS_EQUIBOP there.
