### ISSUE TITLE
[Feature Request]custom plugin list

### ISSUE THREAD

**Issue by kittenvr** [Equicord/Equibop#22]
### Motivation

i want to see the custom plugins listed

### Solution

add the custom plugins in the readme.md

### Alternatives

checking the files

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Equicord feature request

**Comment by Panniku** [comment]
have you ever read https://github.com/equicord/equicord?tab=readme-ov-file

**Comment by thororen1234** [comment]
First this is an equicord feature req.
Second https://github.com/equicord/equicord?tab=readme-ov-file
Third
![image](https://github.com/user-attachments/assets/8b3dcd5f-3232-4dd4-8dbb-71f2e59294d2)

**Comment by kittenvr** [comment]
> have you ever read https://github.com/equicord/equicord?tab=readme-ov-file

yeah its says 100 but only lists a few
