### ISSUE TITLE
Lagging af

### ISSUE THREAD

**Issue by x2b1** [Equicord/Equibop#26]
### Operating System

Windows 11

### What happens when the bug or crash occurs?

overall idk what causes it but the client seems very laggy for me unlike armcord / vesktop / and vencord client and if i try to change my profle pic the lag is so hard i need to manually end the task and re run the equicord to even click anything

### What is the expected behaviour?

i expect yall to fix it 

### How do you recreate this bug or crash?

overall i have almost all plugins enabled so ill upload the list of what i have enabled and you just need to try changing ur pfp for the lag to be insane
![image](https://github.com/user-attachments/assets/4eff9ac6-6a17-4cd7-8474-c12a6dca5ada)
![image](https://github.com/user-attachments/assets/c6945495-2748-4213-b137-d6306a28d68e)
![image](https://github.com/user-attachments/assets/ae3da156-5b52-49f8-8895-59e264cc282a)
![image](https://github.com/user-attachments/assets/bb88dfc0-2d1a-4225-9b78-13ec02ad5c57)
![image](https://github.com/user-attachments/assets/4f478796-2e8d-489a-934b-d8f7c2c60520)
![image](https://github.com/user-attachments/assets/11d63460-3ef8-4fdc-a261-54867858efe9)
![image](https://github.com/user-attachments/assets/d66536d4-dd59-4db6-840c-886a61d84600)
![image](https://github.com/user-attachments/assets/d8d8b185-c4bf-4e66-8fb3-776c25eb4f98)
![image](https://github.com/user-attachments/assets/76ddf2f7-a179-4cc1-94af-31223a875ec9)
![image](https://github.com/user-attachments/assets/7848709e-be8c-4a75-9025-4ebc39f368fd)

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Equibop and Equicord versions
- [X] This issue occurs on an official release (not just the AUR packages)

**Comment by KrystalSkullOfficial** [comment]
please use our support channel in our server so we can trouble shoot this problem better

**Comment by KrystalSkullOfficial** [comment]
Also disable some plugins, if you every plugin we have then its going to be laggy
