### ISSUE TITLE
Custom theme lag

### ISSUE THREAD

**Issue by x2b1** [Equicord/Equibop#27]
### Discord Account

cipalover

### Operating System

Windows 11

### What happens when the bug or crash occurs?

Just look. the theme only makes equicord lag and not any other client so i want yall to fix it
i cant upload this shit directly on github bc too big file size so: https://youtu.be/ovnmBjtUklM

### What is the expected behaviour?

i expect yall to somehow find the issue and fix the lag

### How do you recreate this bug or crash?

just use a custom theme, but i dont use any other themes so it might be just with one particular one or whatever so ill give a link to it: https://www.mediafire.com/file/s9qx8e0vw5advqy/x2b+v2.css/file

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Equibop and Equicord versions
- [X] This issue occurs on an official release (not just the AUR packages)

**Comment by KrystalSkullOfficial** [comment]
please use our support server for support or dont use that theme, noting we can about a laggy theme

**Comment by x2b1** [comment]
it doesnt lag on other clients as showed in the vid so its just an equicord issue

**Comment by KrystalSkullOfficial** [comment]
nothing we can do about a laggy theme

**Comment by thororen1234** [comment]
Looks to be caused by the theme and a combination of plugins that could be enabled.
