### ISSUE TITLE
[Bug] Tray Icon is buggy with flatpak and appimage versions

### ISSUE THREAD

**Issue by athena11778** [Equicord/Equibop#38]
### Discord Account

athena11778

### Operating System

EndeavorOS / Linux Mint 21.3/22

### Linux Only ~ Desktop Environment

KDE on Wayland / Cinnamon on X11

### What happens when the bug or crash occurs?

The tray icon accent colour does not match the select option in Equibop settings.

### What is the expected behaviour?

The tray icon accent should match the selected colours.

### How do you recreate this bug or crash?

1. Install Equibop, either using flatpak or appimage, and try to change colour of tray accent.
![image](https://github.com/user-attachments/assets/7ecbdd48-c2f1-43cf-b8a6-515ecc1cfca0)
![Screenshot_20241021_164520](https://github.com/user-attachments/assets/30b77868-8bcf-45cb-a90e-267e5f3480ba)

### Debug Logs

```
./equibop.appimage                                                                                                                                      [16:46:35]
Checking for update
Gtk-Message: 16:46:39.019: Failed to load module "appmenu-gtk-module"
(node:20887) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 did-stop-loading listeners added to [WebContents]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(Use `equibop.bin --trace-warnings ...` to show where the warning was created)
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
Update for version 2.1.0-rc1 is not available (latest version: 2.1.0-rc1, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
[20930:1021/164640.921343:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[Plugin:MediaDownloader] Using workdir:  /tmp/vencord_mediaDownloader_uwA7C3
[20930:1021/164650.141661:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[20930:1021/164650.149847:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!


```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Equibop and Equicord versions
- [X] This issue occurs on an official release (not just the AUR packages)

**Comment by athena11778** [comment]
as a note, yes, i have experienced the same issue on the NON RC versions as well, this bug has existed for a while.

**Comment by thororen1234** [comment]
It was supposedly removed from settings when I purged the getaccentcolor because of flatpak but ill see if we can add it back.

**Comment by athena11778** [comment]
> It was supposedly removed from settings when I purged the getaccentcolor because of flatpak but ill see if we can add it back.

strange, its still definitely there for me.

**Comment by athena11778** [comment]
Tested it out building from the latest commit, looks like it works now! Thanks!
