### ISSUE TITLE
[Bug] Disabled notification badge reappears after each update

### ISSUE THREAD

**Issue by KaKi87** [Equicord/Equibop#40]
### Discord Account

kaki87

### Operating System

KDE neon 6.2

### Linux Only ~ Desktop Environment

KDE on Wayland

### What happens when the bug or crash occurs?

Notification badge reappears after each update despite being disabled.

### What is the expected behaviour?

Notification badge doesn't reappear.

### How do you recreate this bug or crash?

1. Disable notification badge ;
2. See notification badge disappeared ;
3. Perform update ;
4. See notification badge reappeared ;
5. See notification badge still disabled ;
6. Toggle notification badge back on then off again ;
7. Notification badge finally re-disappears (but will reappear at the next update).

### Debug Logs

No crash.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Equibop and Equicord versions
- [X] This issue occurs on an official release (not just the AUR packages)

**Comment by thororen1234** [comment]
Should be fixed in this [commit](https://github.com/Equicord/Equibop/commit/14bbe0387b663271add471c2204f5b4b499ada95)
