### ISSUE TITLE
[Feature Request] Make Taskbar icons 32x32 instead of 128x128

### ISSUE THREAD

**Issue by ToxicCloud69** [Equicord/Equibop#41]
### Discord Account

toxiccloud69

### Motivation

I am bothered by how the taskbar icons look when they are compressed in my taskbar because of their large size. 

### Solution

Resize taskbar icons to their correct size for Windows which is 32x32 instead.

### Alternatives

I don't think there are alternatives sadly.

### Additional context

I have made custom icons that are 32px by 32px to fix the quality issue, but it seems that the main icon has to be 128x128 because the notification badge breaks otherwise.

128x128 looks like this:
![image](https://github.com/user-attachments/assets/d21489f2-6864-40e9-aa7b-19b5bf4879cd)

32x32 looks like this:
![image](https://github.com/user-attachments/assets/69a0044c-7599-4971-b35e-261e53bb5030)

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Equicord feature request

**Comment by thororen1234** [comment]
Added [here](https://github.com/Equicord/Equibop/commit/14bbe0387b663271add471c2204f5b4b499ada95)

**Comment by verysillycat** [comment]
This was reverted due to it being a ExplorerPatcher issue then ours.

**Comment by ToxicCloud69** [comment]
What the is ExplorerPatcher if i may ask?
