### ISSUE TITLE
[Bug] ExportContacts plugin causes crash when enabled

### ISSUE THREAD

**Issue by pinbuck** [Equicord/Equibop#52]
### Discord Account

evilwizard1041

### Operating System

Fedora 40 (my PC) and Windows 10 (friend's PC)

### Linux Only ~ Desktop Environment

KDE on Wayland

### What happens when the bug or crash occurs?

https://github.com/user-attachments/assets/8678a85d-ffc4-4f8b-8b0c-3fce342cd159

![Screenshot_20241212_130229](https://github.com/user-attachments/assets/7fd2bf47-6576-4110-aee2-6d306f8cc149)

I tested this with ExportContacts enabled by itself, and on a friend's machine with the default plugins after install.

Additional notes:
After the crash recovers using the crash recover plugin, I got a weird side effect I've never seen happen before; the plugins section wouldn't let me search plugins.

I didn't verify this side effect on friend's PC, and it seemed to go away after a bit, or after turning off most all plugins.

### What is the expected behaviour?

Not crashing once I click a friend's profile while using the ExportContacts plugin

### How do you recreate this bug or crash?

1. Enable ExportContacts plugin within Equibop plugins
2. Restart Equibop
3. Click a friend's profile picture, a complete crash of Equibop will then happen.

### Debug Logs

```
pine@BOXOFDOOM:~$ equibop
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: rpm
Checking for update
(node:55729) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 did-stop-loading listeners added to [WebContents]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(Use `equibop --trace-warnings ...` to show where the warning was created)
Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
[55764:1212/125711.358336:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[55764:1212/125712.539347:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[55764:1212/125724.017317:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
pine@BOXOFDOOM:~$ 
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Equibop and Equicord versions
- [X] This issue occurs on an official release (not just the AUR packages)

**Comment by thororen1234** [comment]
Please update Equicord as it was fixed [here](https://github.com/Equicord/Equicord/compare/9bec6e223775...850fadfaba3d)
